name: note_keeper
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  uuid: ^4.3.3
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  http: ^1.2.0
  connectivity: ^3.0.6
  flutter_launcher_icons: ^0.13.1
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/